### ISSUE TITLE
Version Comparison Issue?

### ISSUE THREAD

**Issue by jplandry908** [watanabeyu/react-native-store-version#10]
Hello again. :)

I was just testing a new version of an app on my iOS simulator and discovered a bug with the version checks.

{ error: false, local: '1.1.0', remote: '1.0.3', result: 'new' }

My local version is '1.1.0', but the App Store version is '1.0.3'. The result is 'new' so my code is prompting me to upgrade. Shouldn't it report back 'old' per your example?

"If local(1.0.0) and remote(1.1.0), result is new."

Also for reference, I have used this module in the past for easy version comparisons.
https://www.npmjs.com/package/compare-versions

**Comment by watanabeyu** [comment]
@jplandry908 
thanks your issue.
I will check this bug, and fix it if it is a bug.

**Comment by watanabeyu** [comment]
@jplandry908 
Hi thanks to your issue.
I fixed it bug, and released new version v.1.2.1.

thanks.

**Comment by jplandry908** [comment]
Hi @watanabeyu 

Unfortunately, it appears the bug has not been resolved in your latest update (v1.2.1).

var check = await checkVersion({
        ...
});

This works using 'check-versions' - the upgrade dialog is not triggered.
        if (compareVersions.compare(check.remote, DeviceInfo.getVersion(), '>')) {
            this.setState({
                dialogUpgradeVisible: true
            });
        }

But, this is reporting 'new' incorrectly and triggers the dialog message.
        if (check.result === "new") {
            this.setState({
                dialogUpgradeVisible: true
            });
        }

It is picking up the local and remote versions correctly, but still showing the result as 'new'.

{ error: false, local: '1.1.1', remote: '1.0.4', result: 'new' }
