### ISSUE TITLE
Not working for Play Store -> 403

### ISSUE THREAD

**Issue by kasterlod** [watanabeyu/react-native-store-version#17]
Hello, it's not working for the google play store. Returns 403 - fobidden access. None of play store url is working even if simple fetch. Any tips how to solve this? cc @watanabeyu

**Comment by watanabeyu** [comment]
https://github.com/watanabeyu/react-native-store-version/pull/41

released new version, so close this issue.
Sorry for the long wait for an update.
thanks.
