### ISSUE TITLE
Delay in recognising new ios version

### ISSUE THREAD

**Issue by JeremyBradshaw7** [watanabeyu/react-native-store-version#18]
I release a new version to the app store, it takes about an hour or so to actually appear in the app store (and on the page linked to by `iosStoreURL`), that's normal and Apple's fault - but even when it does eventually appear in the app store, this package is still not picking up that new version for some time afterwards (best guess is a few additional hours. I'll try to narrow that down).

This is impacting our ability to rely on this package for informing iOS users about an upgrade. On Android it works immediately.

**Comment by watanabeyu** [comment]
IOS 's apple store needs time until it's updated, so I can't help it.

**Comment by JeremyBradshaw7** [comment]
Thanks @watanabeyu I know it takes apple about an hour til a new version appears in the stores, but I'm saying that even after the new version appears in the page linked to by `iosStoreURL`, it's still some time before the new version is detected. For example I'm getting this response right now:
![image](https://user-images.githubusercontent.com/36155348/109492299-ab1be000-7a82-11eb-8334-1d8b3a4a647f.png)

where version 1.0.32 went live at about 11am today (40 minutes ago). 

https://apps.apple.com/us/app/competence/id1448472214 shows 1.0.32 since about 11am:
![image](https://user-images.githubusercontent.com/36155348/109492517-0352e200-7a83-11eb-86a7-58b8c7c91559.png)

**Comment by watanabeyu** [comment]
@JeremyBradshaw7 
Since it uses the API of AppStore, there is nothing we can do about it.

> On our last release I monitored it for a few hours but it didn't actually show the new version until I checked it the next day. I'm wondering if there's some caching going on.

If it is cache related, I will make a fix soon to avoid looking at the cache when fetching.

**Comment by JeremyBradshaw7** [comment]
It's now about 3 hours since I saw the new version in the app store but the package is still returning the old version.

**Comment by JeremyBradshaw7** [comment]
Almost certainly is using a previously cached result in the package's fetch, since if I change my countryCode from 'gb' to 'jp' it suddenly works, yet both gb and jp pages show the new version.

**Comment by JeremyBradshaw7** [comment]
Did start recognising the new version the next day as anticipated. The fetch API needs to be adjusted not to cache.

**Comment by adenyx** [comment]
@JeremyBradshaw7 same problem. 
Did you find a solution?

**Comment by JeremyBradshaw7** [comment]
@adenyx no, I was hoping the author would modify the fetches to ensure no caching, as he suggested [here](https://github.com/watanabeyu/react-native-store-version/issues/18#issuecomment-787911028).

**Comment by haianh130799** [comment]
@JeremyBradshaw7 same problem.
Did you find a solution?

**Comment by JeremyBradshaw7** [comment]
@haianh130799 no, waiting for the package author to actually merge 1.3.2, but it's been there since April - I don't know what the delay is.

**Comment by haianh130799** [comment]
@JeremyBradshaw7 can you suggest me for another package ?

**Comment by JeremyBradshaw7** [comment]
@haianh130799 no but you might try just installing from the 1.3.2 PR if you cannot wait for it to be merged. See https://stackoverflow.com/questions/33181297/npm-install-from-github-pull-request

**Comment by haianh130799** [comment]
@JeremyBradshaw7 npm install <user>/<repo>#pull/<id>/head can you suggest me for full command to use 1.3.2 version

**Comment by haianh130799** [comment]
@JeremyBradshaw7 can you help me

**Comment by JeremyBradshaw7** [comment]
Well it will be, I think:

`npm install --save watanabeyu/react-native-store-version#pull/19/head`

or if you use yarn it doesnt need the `pull` part:

`yarn add watanabeyu/react-native-store-version.git#19/head`

but please note I haven't actually verified that the PR actually does what we want it to.

**Comment by haianh130799** [comment]
@JeremyBradshaw7 Do you try it in your application?

**Comment by JeremyBradshaw7** [comment]
@haianh130799 no, did you?

**Comment by haianh130799** [comment]
@JeremyBradshaw7 i haven't tried it yet

**Comment by haianh130799** [comment]
@JeremyBradshaw7 Do you try to change country from jp to us ?

**Comment by JeremyBradshaw7** [comment]
@haianh130799 no, I don't think that will work, as its the previous version you have out there on users' devices that you want detecting the new version, and they will still be using the original country code.

**Comment by haianh130799** [comment]
@JeremyBradshaw7 is there another way to do this like calling the api from the appstore ?

**Comment by JeremyBradshaw7** [comment]
@haianh130799 of course you can hand code your own solution taking into account whether Android or IOS, but that's what this package should take care of for you. I did ask the author whether the PR to fix this can be merged, but no response.

**Comment by haianh130799** [comment]
@JeremyBradshaw7 can you provide me api from appstore to get version ?

**Comment by JeremyBradshaw7** [comment]
@haianh130799 best if you look in the source of this package to see how it does it. Easiest way though is for you to install from the PR as previously suggested.
