### ISSUE TITLE
outdated android store version pattern matching

### ISSUE THREAD

**Issue by nathanwkwong** [watanabeyu/react-native-store-version#31]
The regex inside .getAndroidVersion() from android.js of this package may be outdated such that it can not find the android app version from the pattern matching. I don't know is there any fix for it.

![image](https://user-images.githubusercontent.com/55337066/147898935-baca2848-612c-4db7-badf-7c65682ede41.png)

**Comment by watanabeyu** [comment]
https://github.com/watanabeyu/react-native-store-version/pull/41

released new version, so close this issue.
Sorry for the long wait for an update.
thanks.
