### ISSUE TITLE
issue with Android Play store Version fetching

### ISSUE THREAD

**Issue by hussainimdad004** [watanabeyu/react-native-store-version#39]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-store-version@1.3.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-store-version/dist/android.js b/node_modules/react-native-store-version/dist/android.js
index 469615f..ad10a8f 100644
--- a/node_modules/react-native-store-version/dist/android.js
+++ b/node_modules/react-native-store-version/dist/android.js
@@ -8,7 +8,7 @@ export const getAndroidVersion = async (storeURL = '') => {
         }
         throw new Error('androidStoreURL is invalid.');
     });
-    const matches = response.match(/<span class="htlgb"><div class="IQ1z0d"><span class="htlgb">([0-9]+\.?[0-9]*\.?[0-9]*)<\/span><\/div><\/span>/);
+    const matches = response.match(/\[\[\[['"]((\d+\.)+\d+)['"]\]\],/);
     if (!matches) {
         throw new Error('can\'t get android app version.');
     }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by nuvolarmobileteam** [comment]
Many thanks @hussainimdad004 ,
we'll be using the same patch, we are facing the exact same issue here

**Comment by watanabeyu** [comment]
thanks report @hussainimdad004 
I will fix this issue.

**Comment by purpleh00d** [comment]
> thanks report @hussainimdad004 I will fix this issue.

Hello any updates on the fix?

**Comment by JeremyBradshaw7** [comment]
I'm using the suggested patch for now. Would be get it fixed in the package properly though.

**Comment by iphonic** [comment]
@JeremyBradshaw7 @hussainimdad004 How to install the patch version?

**Comment by JeremyBradshaw7** [comment]
@iphonic ensure you are using [patch-package](https://github.com/ds300/patch-package) then cut & paste Hussain's patch into this file:

![image](https://user-images.githubusercontent.com/36155348/176870485-91e4d245-6bfc-4578-800e-422710b09081.png)

**Comment by iphonic** [comment]
@JeremyBradshaw7 You mean to say I need to use this `yarn add patch-package postinstall-postinstall` will it install patches for all packages I am using? and copy the code for this package and paste where?

It would be great if you can guide me, never used it before.

Thanks.

**Comment by watanabeyu** [comment]
@hussainimdad004 
thanks patch package.
I'm fixing this package, so publish new version tomorrow.
Sorry to keep you waiting...

**Comment by watanabeyu** [comment]
https://github.com/watanabeyu/react-native-store-version/pull/41

released new version, so close this issue.
Sorry for the long wait for an update.
thanks.
