### ISSUE TITLE
Issue with non-JP Apps

### ISSUE THREAD

**Issue by jplandry908** [watanabeyu/react-native-store-version#8]
Thank you so much for creating this. I just wanted to let you know of an issue when trying to get the version of an app not supported in JP.

ios.ts
const response = await fetch(`https://itunes.apple.com/jp/lookup?id=${appID[1]}`).then(r => r.text()).then(r => JSON.parse(r));

Since /jp/ is hard-coded as the country, if the app is only designed for another country (i.e. US), the 'jp' needs to be replaced with that country.  You can probably pull this easily form the App Store URL itself and take whatever the user enters as default. Just a thought.

**Comment by watanabeyu** [comment]
@jplandry908 
Hi thanks!
I will fix it as soon as possible, please wait!

**Comment by watanabeyu** [comment]
@jplandry908 
update version to v1.2.0
please change country like a below code.

```
const check = await checkVersion({
  version: "1.0.0",
  iosStoreURL: 'ios app store url',
  androidStoreURL: 'android app store url',
  country: 'us'
});
```

**Comment by jplandry908** [comment]
That's a great idea to implement it this way. Thanks for the update!
